In [76]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [77]:
# ps = PorterStemmer()

# def process_title(title):
#     new_title = title.lower()
#     new_title = re.sub(r'\$[^\s]+', 'dollar', new_title)
#     new_title = re.sub(r'[^a-z0-9\s]', '', new_title)
#     new_title = re.sub(r'[0-9]+', 'number', new_title)
#     new_title = new_title.split(" ")
#     new_title = list(map(lambda x: ps.stem(x), new_title))
#     new_title = list(map(lambda x: x.strip(), new_title))
#     if '' in new_title:
#         new_title.remove('')
#     return new_title

In [78]:
train=pd.read_csv('Dataset/train.csv')
test=pd.read_csv('Dataset/test.csv')
y_test=pd.read_csv('Dataset/submit.csv')


In [79]:
#Initializ y_train and x_train
train['text_merge'] = train['title'].astype(str) + ' ' + train['author'].astype(str) + ' ' + train['text'].astype(str)
x_train = train['text_merge']
y_train = train.drop(['id','title','author','text','text_merge'],axis=1)
y_train = np.array(y_train)
print(x_train.shape)
print(y_train.shape)

(20800,)
(20800, 1)


In [80]:
#Initializ y_test and x_test
test['text_merge'] = test['title'].astype(str) + ' ' + test['author'].astype(str) + ' ' + test['text'].astype(str)
x_test = test['text_merge']
y_test = y_test.drop(['id'],axis=1)
y_test = np.array(y_test)
x_test

0       Specter of Trump Loosens Tongues, if Not Purse...
1       Russian warships ready to strike terrorists ne...
2       #NoDAPL: Native American Leaders Vow to Stay A...
3       Tim Tebow Will Attempt Another Comeback, This ...
4       Keiser Report: Meme Wars (E995) Truth Broadcas...
                              ...                        
5195    The Bangladeshi Traffic Jam That Never Ends - ...
5196    John Kasich Signs One Abortion Bill in Ohio bu...
5197    California Today: What, Exactly, Is in Your Su...
5198    300 US Marines To Be Deployed To Russian Borde...
5199    Awkward Sex, Onscreen and Off - The New York T...
Name: text_merge, Length: 5200, dtype: object

In [81]:
# x_train_list = x_train.tolist()
tokenizer=Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(x_train)
word_index=tokenizer.word_index
sequences_train = tokenizer.texts_to_sequences(x_train)
X_train = pad_sequences(sequences_train,maxlen=10000,truncating='post',padding='post')
sequences_test = tokenizer.texts_to_sequences(x_test)
X_test = pad_sequences(sequences_test,maxlen=10000,padding='post',truncating='post')
# print(sequences_test)
# print(word_index)
print(X_train)
print(X_train.shape)
print(X_test.shape)
X_test

[[  130  5169  2273 ...     0     0     0]
 [ 2468   111    70 ...     0     0     0]
 [  205     2   720 ...     0     0     0]
 ...
 [10049     9    18 ...     0     0     0]
 [ 1054   178     3 ...     0     0     0]
 [   55  3272     2 ...     0     0     0]]
(20800, 10000)
(5200, 18654)


array([[11142,     4,    36, ...,     0,     0,     0],
       [  223,  9296,  1265, ...,     0,     0,     0],
       [11274,  1676,    96, ...,     0,     0,     0],
       ...,
       [  511,   321,    55, ...,     0,     0,     0],
       [ 1856,    80,  6364, ...,     0,     0,     0],
       [ 6812,  1115, 15373, ...,     0,     0,     0]])